version: '3'

services:
  apache:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: gerador
    restart: always
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
